name: actions-test

on: push

jobs:
  hello:
    name: test one
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
     
      - name: run superlinter
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
